import { parseTimelineData, extractEntities } from "./data-parser"

const RAW_TIMELINE_DATA = `2008-2013
* 2011: Bitcoin Vaults and Xapo's Origins. In 2011, lacking secure storage for his own Bitcoin, early-adopter Wenceslao C. coded his own vault. Friends soon asked to use it, and the idea became Xapo two years later. Xapo was founded by Wenceslao C. and Federico M. as a Bitcoin wallet and vault service but soon expanded into more banking services
* 2012: Gente interesada en Bitcoin. The earliest open and registered meeting was held in Belgrano, Buenos Aires, led by early adopters like Wenceslao C right after the first Bitcoin Halvening. The meetup was promptly titled with this name.
* 2013: Proof of Existence on Bitcoin. The app by @maraoz allowed anyone to verify that a document existed at a certain point in time. Demonstrating ownership, without revealing data.
* 2013: The Security Frontier. @sdlerner and @julianor co-founded Coinspect, an auditing firm that would soon secure code for zCash and its forks, Ledger's wallet firmwares, and Grin's cryptocurrency.
* 2013: Ripio's beginnings. It began as BitPagos, helping merchants trade pesos for bitcoin. It evolved into one of Argentina's most used Bitcoin wallets, and later became a widespread crypto exchange.
* 2013: Crypto education reaches universities. From very early on crypto entered Argentina's classrooms. @RodolfoBits taught classes on wallet creation at ITBA, while Pablo Iglesias led early courses on Bitcoin at UTN.
* December 2013: Argentina, core regional leader in crypto HIGHLIGHT. The first LaBitConf marked this milestone, putting Argentina at the center of Bitcoin in LATAM. Global figures like @ErikVoorhees, Bitcoin Core dev @jgarzik joined, with sponsorships from BitPay, AstroPay and The Bitcoin Magazine. Many core crypto community members would meet and attend this first edition. The conference became an annual traveling event, visiting countries in LATAM, before returning to Buenos Aires in 2016.
2014
* 2014: Bitex and the Bitcoin Rails. It launched with a $2 million investment to link Latin America's markets through Bitcoin and provide a competitive Bitcoin trading platform. By 2016, it launched Remitex, a cross-border remittance service using Bitcoin as a settlement.
* 2014: Casa Voltaire: The Crypto Commune HIGHLIGHT. A group of young programmers turned a house in Palermo, into a crypto coworking space. Founded by @maraoz, many of the early members of the crypto community were frequent visitors of Voltaire including @esneider, @demibrener, Ari M., @yemeljardi, @eordano. Their ethos was: transparency, decentralization, and using crypto to fix broken systems. It became an incubator for several of Argentina's most successful crypto startups: Decentraland, the Ethereum-based virtual world, Muun, a user-friendly self custodial mobile Bitcoin/Lightning wallet, and OpenZeppelin, a smart contract security platform.
* 2014: One of the first crypto R&D labs. Coinfabrik was founded by @sdlerner,  Pablo Yabo and Sebastian Wain. With builders holding years of crypto experience at this point, it became one of the world's first specialized crypto R&D labs and software factories.
* 2014: SatoshiTango: Exchange Beginnings. This year saw the founding of one of Argentina's oldest crypto exchanges by @matiasbari, @NLoterspil, and Mariano C..
2015
* Early 2015: Live Crypto Payments. An experimental project, Streamium enabled real-time video streaming with onchain micropayments, proving crypto could power live content.
* 2015: Zeppelin Solutions HIGHLIGHT. Now known as OpenZeppelin, it was created by @demibrener and @maraoz to explore software solutions and smart contracts during their collaborations at Voltaire. OpenZeppelin is now one of the most known blockchain security companies that created the most widely used smart contract framework.
* 2015: Decentraland: The first blockchain virtual world HIGHLIGHT. @eordano, @yemeljardi, @maraoz and Ari M., envisioned an open-source world owned by its users. A 3D land space that users could purchase using crypto, build content on, and even govern collectively through a DAO. The Decentraland platform officially launched in 2020, allowing users worldwide to explore the world, create avatars, buy NFT wearables, build scenes, and trade land on the marketplace.
* 2015: Signatura and Digital Legitimacy. Between 2014 and 2016, @franamat and @federicobond developed Bitcourt, later renamed Signatura, an early experiment to merge legal validation with Bitcoin's trust model. It began as an arbitration platform where business disputes could be resolved transparently, timestamped, and verifiable onchain. The team later collaborated with CESYT to notarize academic diplomas—the first official educational records anchored to Bitcoin in Argentina. By July 2016, Signatura's private beta went live and signed its first document, marking one of the earliest examples of blockchain used for institutional document authentication.
* November 2015: Rootstock Brings Smart Contracts to Bitcoin. The Rootstock (later RSK) whitepaper was released, outlining a Bitcoin-anchored smart-contract network with Ethereum-like capabilities.
2016
* 2016: Trusted contract libraries. After The DAO hack, OpenZeppelin offered audited, reusable contract libraries that developers could trust. A set of battle-tested Solidity code for ERC-20 tokens, ownership, crowdfunding contracts. It quickly became the industry standard.
* 2016: Protofire. That same year, it emerged from Altoros. Its team supported Gnosis, Maker, Kyber, and The Graph, writing subgraphs, building dashboards, and running early indexer nodes.
2017
* 2017: Decentralized justice. Kleros was founded by @federicoast and pioneered decentralized arbitration using crowdsourced jurors and a native token.
* June 2017: @santisiri publishes the Democracy Earth whitepaper, outlining proof-of-identity (POI), attention mining, UBI and quadratic voting.
* July 2017: Growing Solidity & pioneering standards. Augur hired OpenZeppelin to audit the Serpent compiler, concluding "our back-end team is now in unanimous agreement: "we have to migrate to Solidity." Later in the year, the team built out Coral, a secure token sale framework that enabled ICOs. These are one of many cases where Zeppelin grew the adoption of Solidity.
* 2017: A canonical (WETH9) event. Core contributions by @nanexcool, facilitated the deployment on Ethereum mainnet. WETH established a standardized, secure ERC-20-compliant version of ETH, allowing users to convert ETH to WETH without using a centralized party.
* 2017: First oracles & SAI HIGHLIGHT. Some builders and protocols predate oracles. Maker was one of them. Argentinian developer @nanexcool helped Maker create their own oracles, the first decentralized price feeds that backed the DAI stablecoin with offchain signing and onchain aggregation. Maker's DAI was originally known as SAI (Single-Collateral Dai) when it was deployed by @nanexcool. SAI was a decentralized USD-pegged stablecoin backed solely by ETH, and it quickly became a lifesaver for Argentines facing ~50% annual inflation and strict currency controls.
2018
* 2018: The first DEX. @dmf7z launched EasyTrade — "a decentralized Shapeshift" that let users swap tokens directly onchain.
* 2018: ERC-721. The NFT standard was formalized, and Argentine developers @smpalladino, @eordano and @facuspagnuolo played a role in its implementation and popularization. OpenZeppelin provided open-source ERC-721 library code, guides and security audits, facilitating adoption of the first NFT projects.
* 2018: The first community-organized ETHGlobal hackathon HIGHLIGHT. ETH Buenos Aires was led by @0xtoucan and @ornellacordoba and brought builders from all over the world together for ETHGlobal's third hackathon ever, and the first one held in Latin America. Through volunteering and hacking, ETH Buenos Aires onboarded many of today's community members into crypto.
* 2018: Tokenized wine. Mike B. launched OpenVino, an Argentine initiative to tokenize wine. In May 2018, the entire 2018 harvest (16,384 bottles) was tokenized and offered via a public token sale at cost price.
* May 2018: Argentina's Banco Masventas became the first bank in the country and one of the first globally to use cryptocurrency for cross-border money transfers thanks to a collaboration with Bitex that allowed them to route international payments through Bitcoin instead of Swift.
* 2018: Wibson was an early company developed by Mat T. of Gran Data to create a decentralized marketplace of data.
* 2018: ERC-1271. EOAs can easily sign messages with private keys, but contracts had no private keys. The proposal coauthored by Zeppelin's Fran G. solved this by defining a common interface that contract wallets can implement to prove a signature's validity.
* 2018: Buendólar. @fedeogue launched Buenbit as a crypto exchange focused on stablecoins. By actively marketing DAI savings during the 2020–21 inflation spike with support from the Maker Foundation's outreach, Buenbit attracted thousands of Argentines to crypto.
* 2018: Argentina's first university blockchain lab HIGHLIGHT. Students and professors at the National Technological University in La Plata created Argentina's first university-backed blockchain lab. By the end of the year it had 19 members: 3 professors and 16 students.
* 2018: CryptoMondays began: meetups held to share their views, networking, learning and having a blast.
* 2018: Xivis. It was a Buenos Aires-based software development agency that began contributing and developing closely together with other crypto companies.
* 2018: OpenEthereum. @claberus began contributing to it, a now deprecated client for the Ethereum mainnet. @claberus joined the project and contributed to the network resilience in collaboration with Gnosis and the Ethereum Foundation.
2019
* Early 2019: Minting memories HIGHLIGHT. POAP was born at ETHDenver by @worthalter, where attendees received digital badges as proof of participation. The idea spread quickly. POAPs were soon used for gated voting at EDCON Sydney and was appointed by ETHGlobal to issue POAPs to all 300+ hackers at ETHNewYork. Later that year, the Xivis team built the POAP claim system for Devcon Osaka, allowing attendees to mint NFTs on-site. What began as souvenirs became a new social layer for Ethereum.
* 2019: EthereumBA. The meetups were organized by members of Xivis, @0xtoucan and @saldasoro. It grew into monthly gatherings to share knowledge with collaboration of Maker, Zerion, Synthetix, among other projects.
* 2019: Argentines & Aragon. Contributors like @facuspagnuolo joined the Aragon ecosystem, helping shape Aragon One and the early design of its dispute-resolution system, Aragon Court.
* 2019: Lemon & retail adoption. @lemoncheli and @borjamartels founded a mobile wallet that lets users buy, sell, and earn crypto rewards. Its Visa card with Bitcoin cashback made spending crypto part of everyday retail in Argentina.
* 2019: DiDi & verifiable history. NGO Bitcoin Argentina, with IDB and IOV support, launched the DIDI Project to give Buenos Aires' underserved communities a way to build a verifiable reputation history. Underbanked individuals could record microfinance loan repayments and attest through digital credentials.
* 2019: NXTP Ventures's blockchain vertical. The Argentine-founded VC firm launched a vertical focused on blockchain and crypto, including the RSK Acceleration and Adoption Program to migrate Web2 products onchain.
* 2019: DevconBA at Osaka. If Devcon wouldn't come to Buenos Aires, Buenos Aires would come to Devcon. At Devcon 5 in Osaka, a group of Argentinians began campaigning to bring the conference home. They slipped a "DevconBA" slide into talks and wore DevconWine and DevconMate shirts around the venue. Devconnect has been a long time coming.
2020
* 2020: Launch of BeloApp. A seamless crypto-fiat wallet aimed at freelancers and remote workers in Latin America.
* 2020: DeFi LATAM. The collective, organizing meetups, sustaining the Mateando con DeFi newsletter to spread DeFi education and producing Spanish guides on using MakerDAO, Uniswap, etc. By teaching hundreds of newcomers the DeFi basics, it significantly lowered the entry barriers to DeFi for Argentinians.
* 2020: The Graph & Argentina. @0xtoucan joined The Graph. Since then, contributors from Argentina have become core to The Graph's Core Devs Edge & Node and GraphOps.
* 2020: Yearn & Argentina. Argentines like @SaltyFacu began contributing to Yearn, who pioneered yield aggregation in DeFi, automating farming across protocols to lower costs and compound rewards.
* 2020: Hardhat & Nomic HIGHLIGHT. Hardhat (f.k.a Buidler) is one of the most widely used Ethereum development environments co-founded by @zfran and @alcuadrado. The team developed its console (REPL) and Javascript tasks, its built-in network for debugging. Both team members continue to lead the Hardhat ecosystem development today.
* 2020: KPK. It is founded by @claberus and @elbagococina to manage Gnosis DAO's treasury, introducing non-custodial DeFi solutions for underutilized DAO assets amid DeFi Summer risks. Assets under management grew to $1.8 billion in under three years.
* 2020: Beef(y). A low-cost, automated yield optimizer on Ethereum-compatible chains, it was created by five friends from northern Argentina: @Sirbeefalot, @0xbeefy, @roastby, @superbeefyboy, and @elcarno.
* 2020: Mountain Protocol. A fully collateralized, yield-bearing stablecoin backed by short-term U.S. Treasury bonds was created in Argentina by @mcarrica & @mattiascaricato.
2021
* 2021: Kleros and @santisiri launched Proof of Humanity. A sybil-resistant identity verification protocol to offer decentralized human validation, UBI was launched to stream income to verified humans, it raised $1.2M but faced immediate volatility.
* 2021: Balancer & Argentina. Argentine developers played a central role in Balancer's evolution. In 2020, @facuspagnuolo contributed to V1's core contracts and protocol design. A year later, alongside @mrnventuro and @dmf7z they helped deliver Balancer V2.
* 2021: Num Finance and Real-World Assets. Founded in Buenos Aires in 2021, it introduced stablecoins to help Latin Americans hedge inflation and access DeFi. In 2023, the team raised to expand into Brazil, Colombia, Mexico, and the Middle East, beginning early real-world asset tokenization. In 2025, Num Finance was acquired and has rebranded into Twin Finance bringing fully-backed local stablecoins to bring tokenized investment exposure.
* 2021: Mimic, The Automation Engine. Longtime ecosystem contributors in the Argentina ecosystem @facuspagnuolo, @brunitob and @dmf7z founded Mimic Protocol, a framework to automate onchain strategies and operations. By 2023, Mimic v3 introduced, a modular framework for DeFi automation was launched and it was running over 200,000 tasks monthly.
* 2021: Aave & Argentina. From very early on Argentinians have not only been users, but contributors to the Aave ecosystem. Contributors like JP C., @mptherealmvp, @mgrabina, and @donosonaumczuk worked across DeFi infrastructure,smart contract development for Aave V3, Lens, V4 interfaces and ecosystem growth.
* 2021: Exactly. Exactly Protocol was founded by @GabrielGruber, creating a credit market for fixed and variable DeFi rates. It launched on Ethereum in 2022 and expanded to Optimism in 2023.
* 2021: Xeibo, an Argentine crypto venture firm, supported many Web3 startups. Including local projects like SenseiNode, WakeUp Labs, Welook, Defiant, and Pinta.
2022
* 2022: Identity. The Buenos Aires city government released the whitepaper for TangoID, a SSI platform for citizens to store official documents in wallets and present them selectively via blockchain.
* 2022: The NFT boom. The wave pulled mainstream brands. At Coachella, Absolut.Land in Decentraland drew over twenty thousand visitors from a hundred countries. A few months later, Lemon launched Lemon Nation, an NFT-driven community built around "Lemmys." By midyear, more than 400,000 Lemmys had been minted and distributed to users, marking one of Argentina's largest onchain engagement experiments.
* 2022: Keep3r Network. Wonderland launches it, one of its core initial projects. A decentralized network for projects that need external DevOps, and for external teams to find keeper jobs.
* 2022: SenseiNode & Node Infrastructure. It began operating 50+ validator nodes across networks, expanding Latin America's presence in global blockchain infrastructure. The team launched SenseiStake, a non-custodial staking platform that used NFTs to represent tokenized validators. By June 2023, SenseiNode ranked among the world's earliest adopters of DVT, deploying the first solo cluster on Obol's Alpha mainnet release.
* 2022: ETH Latam. A four-day event that brought the global community of builders and educators to Argentina. While ETHBuenosAires marked the first large-scale Ethereum event in the country, connecting Argentina to the broader ETHGlobal community, and EthereumBA focused on gathering the local ecosystem, ETH Latam combined both worlds: it united communities, highlighted local protocols, and introduced international projects to Argentina.
* 2022: LambdaClass. A tech venture studio, it begins work on CairoVM, a Rust implementation of the Cairo Virtual Machine. Lambda would expand to maintaining Ethereum rust clients with Ethrex, contributing to Commit-Boost among other projects.
2023
* 2023: Invest in Music. It was an onchain media organization cofounded by @saldasoro and Cooper T.. It focused on music NFTs, turning fans into onchain music investors via platforms like Zora and Optimism.
* 2023: The Red Guild. Co-founders @mattaereal @tinchoabbate announced it as a group dedicated to safeguarding Ethereum apps and users through research, education, advocacy, and IRL activation campaigns.
* 2023: Bombo & NFTickets. Music on the front, crypto on the back. It is a platform providing NFT ticketing solutions fully integrated into their entertainment services. In September 2023, it had its first major implementation in Mar del Plata, for a Mariano Mellino show.
* 2023: Ethereum Argentina's first edition. It is a non-profit holding conferences and hackathons to expand the community. Since then it held regional editions at the Universidad de Champagnat in Mendoza and in Córdoba, aiming to reach audiences beyond the capital.
* 2023: Damm Capital. It launches the custodial private DAMMstable fund on Arbitrum in stealth mode for friends and family. Operated through USDT, USDC, and DAI liquidity provision on Uniswap LPs, this marked the beginning of DAMM's market-neutral stablecoin strategies.
* 2023: Aztec & Argentina. Argentines like @mrnventuro and @smpalladino are ongoing contributors to the development of privacy in Ethereum. Among them in 2023, Fernet protocol, a fully permissionless random leader election protocol, proposed by @smpalladino was chosen as the final design for Aztec's Sequencer Selection.
* 2023: WakeUp & DAOs. WakeUp Labs began contributing open-source code to some of the largest DAOs in the crypto ecosystem, such as the "Built Status History Search" on the OP Blockchain. They also partnered with WIN Investments to promote the democratization of the football industry and worked with Num Finance (acquired), a company from the Argentine crypto ecosystem.
* 2023: Kleros began collaborating with the Mendoza provincial court.
2024
* 2024: Argentines become part of the first set of Optimism's Security Council and @gonnaeth becomes Grants Council Lead, where he continues to lead funding in the Superchain today.
* 2024: QuarkID. It went live city-wide in Buenos Aires, using zero-knowledge proofs for secure, self-sovereign IDs. It expanded to include health data and payments, becoming the world's first zk-backed municipal ID system.
* 2024: BootNode & zkSync. BootNode, Web3 venture builder, built the zkSync Azure Smart Contract Wallet dApp, integrating zkSync Era's native Account Abstraction to enable seamless, seed-less Web3 onboarding.
* 2024: We're All Mad Here. Wonderland's contributions continue to grow. In 2024, they developed the Superchain ERC-20 standard and the opUSDC architecture for Optimism. Wonderland also delivered a private oracle solution for Aztec, encrypting both the request and the answer, ensuring no other party than the requester has access to it.
* 2024: SEAL. Argentinians @mattaereal and @pablosabatella joined it, where both are ongoing contributors.
* 2024: Exchange law. The law formally defined virtual assets as digital representations of value used for payments or investments and virtual asset providers, who must register with the National Securities Commission. The law established crypto platforms and custodians as "obliged subjects" and created a centralized and public registry of crypto service providers.
* 2024: Sonata, a music client on Farcaster built on Base, launched as the first dedicated music app there. It was cofounded by @saldasoro and sweetman.eth.
* 2024: Eryx, in collaboration with Manas.Tech, received a Ethereum Foundation ZK Grant for Noirky2: A Plonky2 Backend for Noir.
* 2024: BoulderTech emerges with a mission to bridge Latin America's private markets to the world, offering a platform for turning real-world assets into globally accessible, on-chain investment products.
* 2024: Aleph, the first pop-up city. With 3000 attendees in its first iteration, it served as a hub for crypto innovation and positioned Argentina as the Crypto Capital of the World. The Crecimiento movement emerged from contributors at The Mu, Solow, POAP, Beefy, The Graph and ETHLatam 2022. Later editions, like Aleph de Verano and Aleph March 2025, continued to emphasize growing startups in Argentina.
* 2024: The First PSE Core Argentina. The program was designed for university students with programming experience who want to deepen their knowledge of privacy solutions on Ethereum. A second iteration followed in September 2025 under the name ZKET Core Program.
* 2024: Eryx announced the release of STWO-GPU, open-source prototypes designed to accelerate the execution times of Starkware's STWO prover.
2025
* February 2025: Fat solutions released contributions to the privacy and zk space in Argentina. They released Sumo, a zk-powered social login system using JWT proofs and account abstraction, they released Terry Escape, a multiplayer private shared-state game built with Noir, and contributed to Privacy Pools.
* 2025: Sovra: DID & RWA. Co-founded by @fernandezdiego, it is a zk-validium L2 on Ethereum focused on decentralized identity (DID) and real-world assets (RWAs). It provides infrastructure for governments and citizens to issue/verify credentials privately. It's already serving over 8 million users across Argentina, Mexico, and Colombia.
* 2025: Bootnode co-develops the Open Intents Framework in partnership with Hyperlane and the Ethereum Foundation.
* 2025: Exactly released the Exa App. It features the Exa Card, a crypto-backed credit card available in over 160 countries
* 2025: First regulated tokenization regime. Argentina launches it, allowing real-world assets to be issued and traded under CNV oversight, a key step toward modernizing its capital markets. It aims to launch a one-year regulatory sandbox to test and supervise tokenized asset operations and enables trading through Virtual Asset Service Providers (VASPs).
* 2025: Wonderland began working on Interoperable Addresses for Ethereum, authoring ERC-7930 and CAIP-350 and contributing to ERC-7828, ERC-7683.
* 2025: Argentina, a hub for crypto startups. Long-term opportunities for growth happen by connecting communities, talent, entrepreneurs, and regulators. From the very first edition of Aleph, Crecimiento has aimed to grow the ecosystem of startups with mentorships, competitions and builder programs. As of November 2025, Crecimiento has already incubated 246 startups.`

export const timelineData = parseTimelineData(RAW_TIMELINE_DATA)
export const entities = extractEntities(timelineData)

export function getTimelineData() {
  return timelineData
}
